# Generated by Django 4.2.7 on 2023-11-07 13:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время')),
                ('habit_action', models.TextField(verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('period', models.CharField(choices=[('DAILY', 'каждый день'), ('WEEKLY', 'каждую неделю')], default='DAILY', max_length=15, verbose_name='Периодичность')),
                ('time_to_complete', models.PositiveIntegerField(default=120, verbose_name='Время на выполнение в секундах')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='Награда')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец привычки')),
                ('pleasant_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
